# Generated by Django 6.1.1 on 2026-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('lessons', models.IntegerField()),
                ('direction', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('cyber', 'Cyber Security'), ('robot', 'Robotatexnika'), ('os', 'OS'), ('ai', 'AI'), ('mobile', 'Mobil dasturlash')], max_length=20)),
                ('image', models.ImageField(upload_to='courses_image/')),
            ],
        ),
    ]
